import { Appearance, Dimensions, StyleSheet } from "react-native";
import {
  khusaRed,
  khusaText,
  font,
  xlFont,
  mdSpace,
  smSpace,
  mdFont,
  smRadius,
  smBorder,
  shadow,
  surface_a0,
  surface_a20,
  surface_a10,
  lgSpace,
  brand,
  mdBorder,
  surface_a30,
  lgFont,
  headingFont,
  khusaBlue,
  xsSpace,
  khusaGreen,
  khusaYellow,
} from "../Constants";

export default StyleSheet.create({
  container: {
    flex: 1,
    height: Dimensions.get("window").height - 60,
    justifyContent: "flex-start",
    alignItems: "stretch",
    backgroundColor: surface_a0,
    paddingHorizontal: 4,
  },

  // HEADER //

  headerImage: {
    marginBottom: "0%",
    marginLeft:
      brand === "Apple"
        ? "0%"
        : Dimensions.get("window").width * 0.5 - (35 + 15),
    width: 50,
    height: 50,
    resizeMode: "contain",
    tintColor: Appearance.getColorScheme() === "dark" ? khusaText : null,
  },
  pageHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: smSpace,
    borderRadius: smRadius,
    fontFamily: headingFont,
    backgroundColor: "#e75c55",
    //width: "100%",
    overflow: "hidden",
    marginVertical: smSpace,
    marginHorizontal: smSpace,
  },
  pageHeaderText: {
    fontSize: xlFont,
    fontWeight: "bold",
    textTransform: "uppercase",
    textAlign: "center",
    color: "#ffffff",
  },
  // ANNOUNCEMENT //
  announcement: {
    //backgroundColor: surface_a10,
    margin: smSpace,
    borderRadius: smRadius,
    height: 100,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-start",
    //borderWidth: smBorder,
    //borderColor: khusaText,
    //overflow: "hidden",
    //boxShadow: "6px 6px 9px 0px rgba(0,0,0,0.2)",
  },
  announcementText: {
    height: "100%",
    color: khusaText,
    fontFamily: headingFont,
    fontSize: lgFont,
    padding: smSpace,
  },
  leftSection: {
    flex: 1,
  },
  rightSection: {
    flex: 3,
    height: "100%",
    justifyContent: "center",
    borderTopStartRadius: smRadius,
    borderBottomStartRadius: smRadius,
  },
  leftIcon: {
    bottom: -10,
    left: -10,
    color: khusaText,
    opacity: Appearance.getColorScheme() === "dark" ? 0.1 : 0.25,
    fontSize: 100,
    transform: [{ rotate: "-25deg" }],
  },
  // BOXES //
  flexBox: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    flexGrow: 1,
  },
  flexBoxSingle: {
    display: "flex",
    flexDirection: "column",
  },
  boxGroup: {
    flex: 2,
    flexDirection: "column",
    flexWrap: "wrap",
    justifyContent: "space-evenly",
    alignItems: "stretch",
    marginVertical: mdSpace,
  },
  box: {
    minHeight: 125,
    flex: 1,
    minWidth: "45%",
    // maxWidth: "50%",
    paddingHorizontal: smSpace,
    paddingVertical: smSpace,
    backgroundColor: surface_a10,
    borderRadius: smRadius,
    margin: smSpace,
    alignItems: "center",
    justifyContent: "center",
    //elevation: 2,
    overflow: "hidden",
    boxShadow: "6px 6px 9px 0px rgba(0,0,0,0.2)",
  },
  boxLabel: {
    color: khusaText,
    fontSize: mdFont,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: headingFont,
    // textShadowColor: "#00000070",
    //textShadowOffset: { width: 1, height: 1 },
    // textShadowRadius: 1,
    margin: smSpace,
    zIndex: 1,
  },
  backgroundImage: {
    position: "absolute",
    margin: -10,
  },
  backgroundIcon: {
    position: "absolute",
    bottom: -20,
    right: -15,
    color: khusaText,
    opacity: Appearance.getColorScheme() === "dark" ? 0.75 : 0.75,
    fontSize: 120,
    transform: [{ rotate: "10deg" }],
  },
  // BUTTONS //
  buttonGroup: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    //width: "100%",
    maxHeight: 100,
    paddingVertical: 8,
    backgroundColor: surface_a20,
  },

  // SPINNER //
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 14,
    borderRightWidth: 14,
    borderTopWidth: 28,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: khusaText,
    alignSelf: "center",
  },
  pieGroup: {
    flex: 2,
    //width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  optionsGroup: {
    flex: 2,
    //width: "100%",
    paddingVertical: 5,
    backgroundColor: surface_a0,
  },
  pieOptions: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginHorizontal: 0,
    padding: 5,
  },
  pieOptionStyle: {
    alignItems: "center",
    textAlign: "center",
    backgroundColor: surface_a0,
    fontSize: 20,
    padding: 3,
    color: khusaText,
    borderColor: khusaText,
    width: 250,
    height: 40,
    margin: 5,
  },
  // TEXT //
  h1: {
    color: khusaText,
    marginTop: lgSpace,
    fontSize: xlFont,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: headingFont,
  },
  h2: {
    color: khusaText,
    fontSize: lgFont,
    textAlign: "center",
    fontFamily: headingFont,
    margin: smSpace,
    fontWeight: "bold",
  },
  basicText: {
    color: khusaText,
    marginVertical: smSpace,
  },
  subText: {
    color: khusaText,
    fontSize: 11,
  },
  // PROFILE //
  flexGroup: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "stretch",
    flexWrap: "wrap",
    marginVertical: lgSpace,
  },

  // CARDS //
  card: {
    flexDirection: "row",
    backgroundColor: surface_a10,
    borderColor: surface_a30,
    borderRadius: smRadius,
    padding: mdSpace,
    margin: smSpace,
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: shadow,
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 2,
    shadowOpacity: 0.2,
    elevation: 4,
  },
  cardTextGroup: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  cardTitle: {
    fontSize: lgFont,
    fontWeight: "bold",
    alignItems: "center",
    color: khusaText,
    height: 30,
    fontFamily: headingFont,
  },
  cardText: {
    color: khusaText,
    fontSize: lgFont,
    alignItems: "center",
    fontFamily: font,
  },

  // CONVERSATION STARTER //
  promptArea: {
    flex: 6,
    // width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  promptText: {
    flex: 6,
    color: khusaText,
    //width: "100%",
    fontSize: 32,
    paddingVertical: 75,
    paddingHorizontal: 20,
    textAlign: "center",
    fontFamily: headingFont,
  },
  // SECTIONS //
  section: {
    //width: "100%",
    justifyContent: "center",
    alignItems: "stretch",
  },
  sectionTitle: {
    color: khusaText,
    fontSize: xlFont,
    paddingHorizontal: mdSpace,
    fontWeight: "bold",
    fontFamily: headingFont,
  },
  error: {
    color: khusaText,
    fontSize: xlFont,
    fontWeight: "bold",
    paddingBottom: 50,
    fontFamily: font,
  },
  pageContainer: {
    //height: "100%",
    paddingTop: 10,
    paddingBottom: 25,
    paddingHorizontal: 10,
    backgroundColor: surface_a0,
  },
  downloadBar: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "transparent",
    padding: smSpace,
    alignItems: "center",
  },
  barButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: surface_a10,
    padding: smSpace,
    height: 60,
    alignItems: "center",
    borderRadius: smRadius,
  },
  centeredView: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
    height: "100%",
    width: "100%",
  },
  modalView: {
    width: "100%",
    margin: 10,
    marginBottom: "50%",
    backgroundColor: surface_a10,
    borderRadius: smRadius,
    padding: lgSpace,
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: surface_a0,
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.75,
    shadowRadius: 4,
    elevation: 3,
  },

  button: {
    borderRadius: smRadius,
    paddingHorizontal: 20,
    paddingVertical: 10,
    elevation: 2,
    margin: 5,
    backgroundColor: surface_a30,
  },

  // INPUTS //
  formSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    //width: "100%",
    padding: smSpace,
  },
  inputSection: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: smSpace,
    margin: smSpace,
    borderRadius: smRadius,
    backgroundColor: surface_a10,
  },

  inputStyle: {
    margin: smSpace,
    color: khusaText,
    padding: mdSpace,
    borderWidth: smBorder,
    borderRadius: smRadius,
    borderColor: surface_a30,
    fontFamily: font,
    backgroundColor: surface_a10,
  },
  inputMed: {
    minHeight: 200,
    backgroundColor: surface_a10,
    margin: mdSpace,
    borderWidth: mdBorder,
    borderRadius: smRadius,
    padding: mdSpace,
    color: khusaText,
    borderColor: surface_a30,
    textAlignVertical: "top",
  },

  dropDownContainer: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    marginBottom: lgSpace,
  },
  dropBox: {
    borderWidth: mdBorder,
    borderRadius: smRadius,
    borderColor: surface_a30,
    backgroundColor: surface_a0,
    margin: smSpace,
    width: "95%",
  },
  dropdownStyle: {
    backgroundColor: surface_a0,
    borderColor: surface_a30,
    borderWidth: mdBorder,
    borderBottomLeftRadius: smRadius,
    borderBottomRightRadius: smRadius,
    borderTopWidth: mdBorder,
  },
  dropdownRowStyle: {
    borderBottomColor: surface_a10,
  },
  response: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: xsSpace,
  },
  checkbox: {
    marginHorizontal: lgSpace,
    padding: smSpace,
    fontSize: 50,
    color: khusaRed,
    fontFamily: font,
    borderWidth: 0.5,
    borderRadius: 25,
  },

  smButton: {
    backgroundColor: surface_a10,
    borderRadius: smRadius,
    paddingHorizontal: mdSpace,
  },
});
